### ISSUE TITLE
Low performance on the templates with lots of variables

### ISSUE THREAD

**Issue by gukoff** [Azure-Samples/Iot-Telemetry-Simulator#12]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

Try using a 256KB template with 1000 variables. The simulator will be very slow, generating 1-2 messages per second. 

### Root cause

Building a message from the template `T` and variables `V` has the complexity of `O(T * V)` because of this loop:
https://github.com/Azure-Samples/Iot-Telemetry-Simulator/blob/master/src/IotTelemetrySimulator/TelemetryTemplate.cs#L34-L37

We can make it `O(T + V)` if we format the template in one go instead going through a loop.

#### 1. Preprocess the template, make it aware of the future arguments. 

E.g. turn "abc$.Variable1def" into a structure like ["abc", (variables => variables["Variable1"]), "def"].
This will make formatting it using a dictionary of variables an easy task.

C#'s [composite formatting](https://docs.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting) works in a similar fashion.

#### 2. Precompile a regular expression to substitute the variables in one go.

This regex would have to match all variable names. Here's an example: https://stackoverflow.com/a/1231815/2116625

Our case is more complicated than this example because the variables are only tokenized from the left by the `$.` and not from the right. Understanding what the variable name is in the string like `abc$.Variable1def` is harder than if it were `abc$.(Variable1)def` or if there was a restriction that a variable name in the template can't be followed by a `\w` symbol.

**Comment by gukoff** [comment]
Check out the benchmark of the different solutions and the approximate code:
https://github.com/Azure-Samples/Iot-Telemetry-Simulator/pull/13

Solution 1 that operates with an interleaved structure like `["abc", (variables => variables["Variable1"]), "def"]` performs really well, x100 faster than the current solution on the large inputs.

**Comment by TechPreacher** [comment]
Looks great. Do you mind changing the code to use solution 1?

**Comment by gukoff** [comment]
Will do in #15

**Comment by TechPreacher** [comment]
Thanks for improving the performance with #15!
