### ISSUE TITLE
Azure IoT Hub stress testing issues

### ISSUE THREAD

**Issue by prabirkrsarkar** [Azure-Samples/Iot-Telemetry-Simulator#19]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

> 1. We could only generate 259 IoT Hub identities when we ran the docker container "azureiot-simulatordeviceprovisioning" as given in the document.
 
  2. Running the "azureiot-telemetrysimulator" docker container could only generate 70 odd messages. Got an error while sending telemetry.

 3.  When we ran the AZ Cli script as mentioned in "Generating high volume of telemetry" section of the doc it didn't generate any load (~ 70 messages is what we see in IoT Hub usage.

### Any log messages given by the failure
>  
![Screenshot from 2021-06-25 19-15-13](https://user-images.githubusercontent.com/6105319/124110960-69c62c00-da86-11eb-9e50-77f9a78a29a6.png)

### Expected/desired behavior
> We expected to see 1000 device identities in IoT Hub and a huge traffic from the devices.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Ran this from my Ubuntu 20.04
### Versions
> We used the latest version of this tool

### Mention any other details that might be useful

> --------------------------------------------------------------- We are trying to do a Stress testing on our Azure IoT Hub.
> Thanks! We'll be in touch soon.

**Comment by gukoff** [comment]
### About `azureiot-simulatordeviceprovisioning `

> We could only generate 259 IoT Hub identities when we ran the docker container "azureiot-simulatordeviceprovisioning" as given in the document.

Does the tool give return any errors?

### About `azureiot-telemetrysimulator `

The line `Errors sending telemetry == 0` means there were no errors. I agree it looks confusing, we should change it to `No errors sending telemetry` or omit it altogether :)

From what I see in the console output, the simulator was configured to send 10 messages (`MessageCount=10`) from a single device (`DeviceCount=1`).

To generate high load, you probably want to start the container with `MessageCount=0` (this means infinite messages) and lower the pause between messages (`Interval`). 

And if you want to simulate traffic from multiple devices, raise `DeviceCount` and/or start multiple containers with different `DeviceIndex` or `DevicePrefix`.

Also keep in mind that IoTHub [implements rate limiting](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-quotas-throttling). Depending on your IoTHub tier / IoT Hub units, it might throttle your traffic at e.g. 100 messages per second.

---

If this doesn't resolve the issue, could you please:
1. Paste the command with which you start the simulator;
2. Describe your goal in more detail? As in: how much load do you want to generate? how many devices are you required to simulate?

**Comment by prabirkrsarkar** [comment]
Thanks @gukoff I worked like a breeze.
