### ISSUE TITLE
typo for utf8 of content encoding

### ISSUE THREAD

**Issue by kenakamu** [Azure-Samples/Iot-Telemetry-Simulator#4]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Set up routing in IoT Hub
> Run the simulator and send telemetry to IoT Hub
> It won't be routed as expected.

To fix the issue, i need to change the value below from "utf8" to "utf-8"
https://github.com/Azure-Samples/Iot-Telemetry-Simulator/blob/master/src/IotTelemetrySimulator/IotHubSender.cs#L12

**Comment by TechPreacher** [comment]
Hi! Thanks for bringing this up! I have changed the code accordingly. Thank you for your contribution!
